apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
  namespace: services
spec:
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi